name: Mod repo
run-name: "Mod repo"
on:
  repository_dispatch:
    types: [tracker_trigger]

permissions:
  contents: write

jobs:
  inject-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          token: ${{ secrets.GH_TOKEN }}

      # Step processing resource checks and copying (Boot & Fonts detailed)
      - name: Modify uploadROM.sh Script
        if: ${{ github.event.client_payload.enable_mod_uploadrom != 'false' }}
        shell: bash
        run: |
          if [ -f ./uploadROM.sh ]; then
            echo "Modify uploadROM.sh script..."
            
            sed -i 's/ONEDRIVE_REMOTE=.*/ONEDRIVE_REMOTE="nothings-toolbuild"/g' ./uploadROM.sh
            
            if grep -q '--folder_id "1aJw0uWIMD7Yc1n4O1mjbI0YLHjRevfxl"' ./uploadROM.sh; then
              echo "Folder ID is already correct. Skipping update."
            else
              echo "Updating Folder ID..."
              sed -i 's/--folder_id "[^"]*"/--folder_id "1aJw0uWIMD7Yc1n4O1mjbI0YLHjRevfxl"/g' ./uploadROM.sh
            fi
            
            sed -i '/rm -rf \$work_dir\/out/d' ./uploadROM.sh
            sed -i '/rm -rf \$work_dir\/build/d' ./uploadROM.sh
            
            perl -0777 -pi -e 's/(if\s+\[\[\s+\$rom_os\s+==\s+"MIUI"\s+\]\];\s+then.*?upload\s+"Error uploading file to OneDrive: \$FILENAME"\s*\n\s*)exit 1(\s*\n\s*}\s*\n\s*else.*?upload\s+"Error uploading file to OneDrive: \$FILENAME"\s*\n\s*)exit 1/\1\2/sg' ./uploadROM.sh
            
            sed -i '/upload "Error uploading file to Google Drive"/{n; /exit 1/d}' ./uploadROM.sh
            
            echo "Script modification complete!"
          else
            echo "uploadROM.sh file not found!"
            exit 1
          fi

      - name: Inject Packages into build.yml
        if: ${{ github.event.client_payload.enable_inject_packages != 'false' }}
        run: |
          python3 - << 'EOF'
          import os
          build_path = ".github/workflows/build.yml"
          if os.path.exists(build_path):
              with open(build_path, "r", encoding="utf-8") as f:
                  lines = f.readlines()
              
              if any("pip3 install lz4" in line for line in lines):
                  print("Line 'sudo pip3 install lz4' already exists in build.yml, skipping.")
                  exit(0)
                  
              start_idx = -1
              for i, line in enumerate(lines):
                  if "Install tools and send start notification" in line:
                      start_idx = i
                      break
              
              if start_idx != -1:
                  print("Found step 'Install tools and send start notification', checking and inserting...")
                  
                  target_insert_idx = -1
                  for i in range(start_idx, len(lines)):
                      if i > start_idx and lines[i].strip().startswith("- name:"):
                          break
                      if "sudo pip3 install setuptools" in lines[i] or "sudo pip3 install ConfigObj" in lines[i]:
                          target_insert_idx = i
                  
                  if target_insert_idx == -1:
                      for i in range(start_idx, len(lines)):
                          if "python notify.py start" in lines[i]:
                              target_insert_idx = i - 1
                              break

                  if target_insert_idx != -1:
                      line_target = lines[target_insert_idx]
                      indent_size = len(line_target) - len(line_target.lstrip())
                      step_indent = " " * indent_size
                      
                      lines.insert(target_insert_idx + 1, f"{step_indent}sudo pip3 install lz4 2>&1 | tee -a build_action.log\n")
                      
                      with open(build_path, "w", encoding="utf-8") as f:
                          f.writelines(lines)
                      print("Inserted 'sudo pip3 install lz4' into Install tools block successfully!")
                  else:
                      print("Appropriate position not found in Install tools block.")
              else:
                  print("Step 'Install tools and send start notification' not found in build.yml.")
          EOF

      - name: Modify packROM.sh Script
        if: ${{ github.event.client_payload.enable_mod_packrom != 'false' }}
        shell: bash
        run: |
          if [ -f ./packROM.sh ]; then
            echo "Removing --sparse flag in packROM.sh..."
            sed -i 's/mkfs.erofs \(.*\)--sparse \(.*\)/mkfs.erofs \1\2/g' ./packROM.sh
            echo "Flag removal complete!"
          else
            echo "File packROM.sh not found."
          fi

      - name: Patch genInstall.sh
        if: ${{ github.event.client_payload.enable_patch_geninstall != 'false' }}
        shell: bash
        run: |
          FILE="./bin/ddevice/genInstall.sh"
        
          if grep -q '^#chinh-sua-genInstall.sh$' "$FILE"; then
            echo "Already patched."
            exit 0
          fi
        
          perl -0pi -e 's/device_code=\$\(cat \$work_dir\/bin\/ddevice\/device_code\.txt 2>\/dev\/null\)/device_code=\$\(cat \$work_dir\/bin\/ddevice\/device_code.txt 2>\/dev\/null\)\n\ncodename="\$device_code"\nfor s in EEAGlobal EEAGLOBAL Global GLOBAL EEA IN RU TR TW ID JP KR; do\n    codename="\${codename%\$s}"\ndone/s' "$FILE"
          sed -i 's/"Codename": "${device_code}"/"Codename": "${codename}"/' "$FILE"
          sed -i '1i #chinh-sua-genInstall.sh' "$FILE"
          echo "Patched genInstall.sh successfully."

      - name: Modify functions.sh Script
        if: ${{ github.event.client_payload.enable_sync_functionssh != 'false' }}
        shell: bash
        run: |
          if [ -f ./functions.sh ]; then
            echo "📝 Tiến hành cập nhật hàm extract_partition trong ./functions.sh..."
            sed -i 's|extract.erofs -x -i ${part_img} -o ${target_dir}/${part_name%.*}|extract.erofs -x -i ${part_img} -o ${target_dir} > /dev/null 2>\&1|g' ./functions.sh
            echo "✅ Đã cập nhật đường dẫn xả EROFS thành công!"
          else
            echo "⚠️ Không tìm thấy file ./functions.sh."
          fi

      - name: Push changes to Repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add .github/workflows/build.yml uploadROM.sh ./bin/modfile/UpdateFile/Fonts/update.sh packROM.sh ./bin/vbpatcher.py ./bin/package/DISABLE_AVB/DISABLEavb.sh ./bin/ddevice/fetchINFO.sh ./bin/ddevice/DEBLOAT/APPLIST.txt ./bin/ddevice/genInstall.sh functions.sh
          git commit -m "Automated: Sync steps, fetchINFO.sh and update APPLIST.txt" || echo "No changes to commit"
          
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git"
          git push origin main
